#!/bin/bash
#
# Note runlevel 2345, 86 is the Start order and 85 is the Stop order
#
# chkconfig: 2345 86 85
# description: The upload app server.
#
# Below is the source function library, leave it be
. /etc/init.d/functions

# We need environment variables for passwords and the likes
. /home/ec2-user/.bash_profile


FOREVER=/usr/bin/forever
UPLOAD_SCRIPT_HOME=/home/ec2-user/elvis-upload
UPLOAD_SERVER_SCRIPT=$UPLOAD_SCRIPT_HOME/server.js
SERVICE_NAME=upload

# options
LOGFILE=/var/log/admin.log
LOCKFILE=/var/lock/subsys/upload
MIN_UPTIME=5000
SPIN_SLEEP_TIME=2000

start(){
        cd $UPLOAD_SCRIPT_HOME
        $FOREVER \
           --workingDir $UPLOAD_SCRIPT_HOME \
           -a \
           --pidFile $LOCKFILE \
           -l $LOGFILE \
           --minUptime $MIN_UPTIME \
           --spinSleepTime $SPIN_SLEEP_TIME \
           start $UPLOAD_SERVER_SCRIPT
}

stop(){
        $FOREVER stop $UPLOAD_SERVER_SCRIPT
}

restart(){
         stop
         start
}

case "$1" in
        start)
                echo "Start service SERVICE_NAME"
                start
                ;;
        stop)
                echo "Stop service SERVICE_NAME"
                stop
                ;;
        restart)
                echo "Restart service SERVICE_NAME"
                restart
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
                ;;
esac
